name = "ElcondDatas"
uuid = "394f4165-0384-4d45-bd9d-522f0e3aa673"
authors = ["= <=> and contributors"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
NevanlinnaCalc = "48b6fe86-65da-47d3-b19c-ae6a21acf2c8"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
